version: '3'

services:
  # database container's
  db:
    image: postgres:10
    restart: "on-failure" 
    volumes:
      - db1_volume:/var/lib/postgresql/data
    networks:
      - database1_network

  # web container (django + gunicorn)
  djangoapp:
    build: .
    restart: "on-failure"
    environment:
      - DJANGO_SETTINGS_MODULE
    volumes:
      - .:/opt/services/djangoapp/src
      - static:/opt/services/djangoapp/static
      - media:/opt/services/djangoapp/media
    networks:
      - database1_network
      - nginx_network
    depends_on:
     - db

  # reverse proxy container (nginx)
  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static:/opt/services/djangoapp/static
      - media:/opt/services/djangoapp/media
    networks:
      - nginx_network
    depends_on:
      - djangoapp


networks:
  database1_network:
    driver: bridge
  nginx_network:
    driver: bridge
  
volumes:
  db1_volume:
  static:
  media:
  