version: '3'

services:
  # database container's
  db:
    image: postgres:13.4-alpine
    restart: "always" 
    volumes:
      - db:/var/lib/postgresql/data
    expose:
      - "5432"
    env_file:
      - .db_env
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    networks:
      - database1_network

  # web container (django + gunicorn)
  djangoapp:
    build: .
    restart: "always"
    environment:
      - DJANGO_SETTINGS_MODULE
    volumes:
      - .:/opt/services/djangoapp/src
      - static:/opt/services/djangoapp/src/static
      - media:/opt/services/djangoapp/src/media
    networks:
      - database1_network
      - nginx_network
    depends_on:
     - db

  # reverse proxy container (nginx)
  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static:/opt/services/djangoapp/src/static
      - media:/opt/services/djangoapp/src/media
    networks:
      - nginx_network
    depends_on:
      - djangoapp


networks:
  database1_network:
    driver: bridge
  nginx_network:
    driver: bridge
  
volumes:
  db:
  static:
  media:
  